POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username" : "khannedy",
  "name" : "Eko Khannedy",
  "password" : "rahasia"
}

### Login

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username" : "khannedy",
  "password" : "rahasia12345"
}

### Get User
GET http://localhost:3000/api/users/current
Accept: application/json
Authorization: b8f2ca2c-77cc-43ae-91f1-86d3c9903867

### Logout User
DELETE http://localhost:3000/api/users/current
Accept: application/json
Authorization: b8f2ca2c-77cc-43ae-91f1-86d3c9903867

### Update User
PATCH http://localhost:3000/api/users/current
Accept: application/json
Content-Type: application/json
Authorization: b8f2ca2c-77cc-43ae-91f1-86d3c9903867

{
  "password" : "rahasia12345"
}

### Create contact
POST http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: b8f2ca2c-77cc-43ae-91f1-86d3c9903867

{
  "first_name" : "Joko",
  "last_name" : "Morro",
  "email" : "joko@example.com",
  "phone" : "089999999"
}

### Update contact
PUT http://localhost:3000/api/contacts/2012
Content-Type: application/json
Accept: application/json
Authorization: b8f2ca2c-77cc-43ae-91f1-86d3c9903867

{
  "first_name" : "Budi",
  "last_name" : "Morro",
  "email" : "budi@example.com",
  "phone" : "089999999"
}


### Get contact
GET http://localhost:3000/api/contacts
Accept: application/json
Authorization: b8f2ca2c-77cc-43ae-91f1-86d3c9903867

### Delete contact
DELETE http://localhost:3000/api/contacts/2013
Accept: application/json
Authorization: b8f2ca2c-77cc-43ae-91f1-86d3c9903867

### Search contact
GET http://localhost:3000/api/contacts?name=eko
Accept: application/json
Authorization: b8f2ca2c-77cc-43ae-91f1-86d3c9903867

### Create Address
POST http://localhost:3000/api/contacts/2015/addresses
Content-Type: application/json
Accept: application/json
Authorization: b8f2ca2c-77cc-43ae-91f1-86d3c9903867

{
  "street" : "jalan contoh",
  "city" : "kota contoh",
  "province" : "provinsi contoh",
  "country" : "negara contoh",
  "postal_code" : "23434"
}

### Get Address
GET http://localhost:3000/api/contacts/2015/addresses/656
Accept: application/json
Authorization: b8f2ca2c-77cc-43ae-91f1-86d3c9903867

### List Address
GET http://localhost:3000/api/contacts/2015/addresses
Accept: application/json
Authorization: b8f2ca2c-77cc-43ae-91f1-86d3c9903867

### Update Address
PUT http://localhost:3000/api/contacts/2015/addresses/656
Content-Type: application/json
Accept: application/json
Authorization: b8f2ca2c-77cc-43ae-91f1-86d3c9903867

{
  "street" : "jalan contoh updated",
  "city" : "kota contoh updated",
  "province" : "provinsi contoh",
  "country" : "negara contoh",
  "postal_code" : "23434"
}

### Remove Address
DELETE http://localhost:3000/api/contacts/2015/addresses/657
Accept: application/json
Authorization: b8f2ca2c-77cc-43ae-91f1-86d3c9903867